<?php
require __DIR__.'/includes/functions.php'; $title='Shop the collection';
$where=['p.active=1']; $params=[];
$search=mb_substr(get('q'),0,100); $category=(int)get('category');
if($search!=='') { $where[]='(p.name LIKE ? OR p.keywords LIKE ? OR c.name LIKE ?)'; array_push($params,"%$search%","%$search%","%$search%"); }
if($category>0) { $where[]='p.category_id=?'; $params[]=$category; }
foreach(['min'=>'>=','max'=>'<='] as $key=>$op) if(is_numeric(get($key))) { $where[]="COALESCE(p.sale_price,p.price) $op ?"; $params[]=max(0,(float)get($key)); }
if((float)get('rating')>0) { $where[]='p.rating>=?'; $params[]=min(5,(float)get('rating')); }
$sorts=['newest'=>'p.created_at DESC,p.id DESC','popular'=>'sold DESC,p.id DESC','low'=>'COALESCE(p.sale_price,p.price) ASC','high'=>'COALESCE(p.sale_price,p.price) DESC','rating'=>'p.rating DESC,p.id DESC'];
$sort=get('sort','newest'); $order=$sorts[$sort] ?? $sorts['newest'];
$clause=implode(' AND ',$where); $count=(int)one("SELECT COUNT(*) n FROM products p LEFT JOIN categories c ON c.id=p.category_id WHERE $clause",$params)['n'];
$pages=max(1,(int)ceil($count/8)); $page=min($pages,max(1,(int)get('page','1'))); $offset=($page-1)*8;
$products=all("SELECT p.*,c.name category_name,(SELECT COALESCE(SUM(oi.quantity),0) FROM order_items oi JOIN orders o ON o.id=oi.order_id WHERE oi.product_id=p.id AND o.status<>'Cancelled') sold FROM products p LEFT JOIN categories c ON c.id=p.category_id WHERE $clause ORDER BY $order LIMIT 8 OFFSET $offset",$params);
require ROOT.'/includes/header.php'; ?>
<div class="page-heading"><p class="eyebrow">YOUR NEXT FAVORITE IS HERE</p><h1>The <span class="gradient-text">collection.</span></h1><p>Good design. Everyday possibilities.</p></div><div class="shop-layout"><aside class="glass filters"><h2>Find your fit</h2><form method="get"><label>Search<input name="q" value="<?= e($search) ?>" class="form-control" placeholder="Products, keywords…"></label><label>Category<select name="category" class="form-select"><option value="">All categories</option><?php foreach(categories() as $c): ?><option value="<?= $c['id'] ?>" <?= $category===$c['id']?'selected':'' ?>><?= e($c['name']) ?></option><?php endforeach; ?></select></label><div class="row g-2"><label class="col-6">Min price<input type="number" min="0" step="0.01" name="min" value="<?= e(get('min')) ?>" class="form-control" placeholder="₱0"></label><label class="col-6">Max price<input type="number" min="0" step="0.01" name="max" value="<?= e(get('max')) ?>" class="form-control" placeholder="Any"></label></div><label>Rating<select name="rating" class="form-select"><?php foreach(['0'=>'All ratings','4'=>'4★ and up','3'=>'3★ and up'] as $v=>$label): ?><option value="<?= $v ?>" <?= get('rating','0')===(string)$v?'selected':'' ?>><?= $label ?></option><?php endforeach; ?></select></label><label>Sort by<select name="sort" class="form-select"><?php foreach(['newest'=>'Newest arrivals','popular'=>'Most popular','low'=>'Price: low to high','high'=>'Price: high to low','rating'=>'Top rated'] as $v=>$label): ?><option value="<?= $v ?>" <?= $sort===$v?'selected':'' ?>><?= $label ?></option><?php endforeach; ?></select></label><button class="btn btn-accent w-100">Apply filters</button><a class="btn btn-link w-100" href="<?= url('shop.php') ?>">Reset filters</a></form></aside><section><div class="results-heading"><span><?= $count ?> products<?= $search?' for “'.e($search).'”':'' ?></span><span>Made for your everyday.</span></div><div class="product-grid shop-grid"><?php foreach($products as $p) require ROOT.'/includes/product-card.php'; ?></div><?php if(!$products): ?><div class="empty-state"><i class="fa-solid fa-magnifying-glass"></i><h2>No matches just yet.</h2><p>Try another keyword or reset your filters.</p></div><?php endif; ?><nav class="pagination-nav" aria-label="Product pages"><?php for($i=1;$i<=$pages;$i++): ?><a class="<?= $page===$i?'active':'' ?>" <?= $page===$i?'aria-current="page"':'' ?> href="<?= url('shop.php?'.http_build_query(array_merge($_GET,['page'=>$i]))) ?>"><?= $i ?></a><?php endfor; ?></nav></section></div>
<?php require ROOT.'/includes/footer.php'; ?>
