<?php require dirname(__DIR__).'/includes/functions.php'; require_admin(); $error='';
if($_SERVER['REQUEST_METHOD']==='POST') { check_csrf(); try {
 $id=(int)post('id'); $c=$id?one('SELECT * FROM categories WHERE id=?',[$id]):null; if($id && !$c) throw new DomainException('Category not found.');
 if(post('action')==='delete') { if(one('SELECT id FROM products WHERE category_id=? LIMIT 1',[$id])) throw new DomainException('Reassign products in this category before deleting it.'); q('DELETE FROM categories WHERE id=?',[$id]); }
 elseif(post('action')==='save') { $name=require_text(post('name'),'Category name',2,80); $image=upload_image('image','categories') ?? ($c['image'] ?? 'assets/images/electronics.svg'); if($id) q('UPDATE categories SET name=?,image=? WHERE id=?',[$name,$image,$id]); else q('INSERT INTO categories(name,image) VALUES(?,?)',[$name,$image]); }
 else throw new DomainException('Unknown action.'); flash('Category saved.'); go('admin/categories.php');
 } catch(DomainException $ex) { $error=$ex->getMessage(); } catch(PDOException $ex) { if($ex->getCode()!=='23000') throw $ex; $error='Category name already exists or category is in use.'; } }
$c=get('edit')?one('SELECT * FROM categories WHERE id=?',[(int)get('edit')]):null; $title='Categories'; require __DIR__.'/_header.php'; ?>
<section class="glass p-4 mb-4"><h2><?= $c?'Edit category':'Add category' ?></h2><form method="post" enctype="multipart/form-data"><?= csrf() ?><input type="hidden" name="id" value="<?= (int)($c['id'] ?? 0) ?>"><div class="row"><label class="col-md-6">Name<input name="name" class="form-control" maxlength="80" value="<?= e(post('name',$c['name'] ?? '')) ?>" required></label><label class="col-md-6">Image (JPG, PNG, WebP · max 4 MB)<input type="file" name="image" accept="image/jpeg,image/png,image/webp" class="form-control"></label></div><button class="btn btn-accent" name="action" value="save">Save category</button><?php if($c): ?><a class="btn btn-link" href="<?= url('admin/categories.php') ?>">Cancel edit</a><?php endif; ?></form></section><div class="category-grid admin-categories"><?php foreach(categories() as $row): ?><article class="glass p-3"><img class="w-100" src="<?= image_url($row['image']) ?>" alt="" width="250" height="210"><h3><?= e($row['name']) ?></h3><div class="d-flex gap-2"><a class="btn btn-soft btn-sm" href="<?= url('admin/categories.php?edit='.$row['id']) ?>">Edit</a><form method="post" data-confirm="Delete this empty category?"><?= csrf() ?><input type="hidden" name="id" value="<?= $row['id'] ?>"><button name="action" value="delete" class="btn btn-outline-danger btn-sm">Delete</button></form></div></article><?php endforeach; ?></div><?php require __DIR__.'/_footer.php'; ?>
