<?php require dirname(__DIR__).'/includes/functions.php'; require_admin(); $error='';
if($_SERVER['REQUEST_METHOD']==='POST') { check_csrf(); try {
 $id=(int)post('id'); $code=strtoupper(post('code')); if(!preg_match('/^[A-Z0-9_-]{3,40}$/',$code)) throw new DomainException('Code needs 3–40 letters, numbers, hyphens or underscores.');
 $type=post('type'); $value=filter_var(post('value'),FILTER_VALIDATE_FLOAT); $minimum=filter_var(post('minimum'),FILTER_VALIDATE_FLOAT); $expiry=post('expires_at'); $d=DateTime::createFromFormat('!Y-m-d',$expiry);
 if(!in_array($type,['percent','fixed'],true) || $value===false || $value<=0 || $value>9999999999 || ($type==='percent' && $value>100) || $minimum===false || $minimum<0 || $minimum>9999999999 || !$d || $d->format('Y-m-d')!==$expiry) throw new DomainException('Enter valid discount, minimum and expiry values.');
 $data=[$code,$type,$value,$minimum,$expiry,isset($_POST['active'])?1:0];
 if($id) q('UPDATE coupons SET code=?,type=?,value=?,minimum=?,expires_at=?,active=? WHERE id=?',array_merge($data,[$id])); else q('INSERT INTO coupons(code,type,value,minimum,expires_at,active) VALUES(?,?,?,?,?,?)',$data);
 flash('Coupon saved.'); go('admin/coupons.php');
 } catch(DomainException $ex) { $error=$ex->getMessage(); } catch(PDOException $ex) { if($ex->getCode()!=='23000') throw $ex; $error='Coupon code already exists.'; } }
$c=get('edit')?one('SELECT * FROM coupons WHERE id=?',[(int)get('edit')]):null; $title='Coupons'; require __DIR__.'/_header.php'; ?>
<section class="glass p-4 mb-4"><h2><?= $c?'Edit coupon':'Create coupon' ?></h2><form method="post"><?= csrf() ?><input type="hidden" name="id" value="<?= (int)($c['id'] ?? 0) ?>"><div class="row g-3"><?php foreach(['code'=>['Code','text'],'value'=>['Discount value','number'],'minimum'=>['Minimum subtotal (₱)','number'],'expires_at'=>['Expires on','date']] as $key=>[$label,$type]): ?><label class="col-md-6"><?= $label ?><input name="<?= $key ?>" type="<?= $type ?>" class="form-control" value="<?= e(post($key,(string)($c[$key] ?? ($key==='minimum'?'0':'')))) ?>" <?= $type==='number'?'min="0" step="0.01"':'' ?> required></label><?php endforeach; ?><label class="col-md-6">Type<select name="type" class="form-select"><option value="percent">Percentage (%)</option><option value="fixed" <?= ($c['type'] ?? '')==='fixed'?'selected':'' ?>>Fixed amount (₱)</option></select></label></div><label class="check-label"><input type="checkbox" name="active" <?= ($c['active'] ?? 1)?'checked':'' ?>> Enabled</label><button class="btn btn-accent">Save coupon</button><a class="btn btn-link" href="<?= url('admin/coupons.php') ?>">New coupon</a></form></section><div class="glass p-3 table-responsive"><table class="table"><thead><tr><th>Code</th><th>Discount</th><th>Minimum</th><th>Expiry</th><th>Status</th><th></th></tr></thead><tbody><?php foreach(all('SELECT * FROM coupons ORDER BY id DESC') as $row): ?><tr><td><?= e($row['code']) ?></td><td><?= $row['type']==='percent'?e($row['value']).'%':money($row['value']) ?></td><td><?= money($row['minimum']) ?></td><td><?= e($row['expires_at']) ?></td><td><?= $row['active']?'Enabled':'Disabled' ?></td><td><a href="<?= url('admin/coupons.php?edit='.$row['id']) ?>">Edit ↗</a></td></tr><?php endforeach; ?></tbody></table></div><?php require __DIR__.'/_footer.php'; ?>
