<?php require dirname(__DIR__).'/includes/functions.php'; require_admin(); $error='';
// Forward-only transitions keep cancellation and inventory restoration deterministic.
$transitions=['Pending'=>['Confirmed','Cancelled'],'Confirmed'=>['Processing','Cancelled'],'Processing'=>['Shipped','Cancelled'],'Shipped'=>['Delivered'],'Delivered'=>[],'Cancelled'=>[]];
if($_SERVER['REQUEST_METHOD']==='POST') { check_csrf(); try {
 db()->beginTransaction(); $o=one('SELECT * FROM orders WHERE id=? FOR UPDATE',[(int)post('id')]); $status=post('status');
 if(!$o || !in_array($status,$transitions[$o['status']],true)) throw new DomainException('This status change is not allowed. Refresh the order.');
 if($status==='Cancelled') { $items=all('SELECT product_id,SUM(quantity) qty FROM order_items WHERE order_id=? AND product_id IS NOT NULL GROUP BY product_id ORDER BY product_id',[$o['id']]); foreach($items as $item) q('UPDATE products SET stock=stock+? WHERE id=?',[$item['qty'],$item['product_id']]); }
 q('UPDATE orders SET status=? WHERE id=?',[$status,$o['id']]); db()->commit(); flash('Order updated.'); go('admin/orders.php?id='.$o['id']);
 } catch(DomainException $ex) { if(db()->inTransaction()) db()->rollBack(); $error=$ex->getMessage(); } }
$order=get('id')?one('SELECT * FROM orders WHERE id=?',[(int)get('id')]):null; $title='Orders'; require __DIR__.'/_header.php';
if($order): require ROOT.'/includes/order-detail.php'; ?>
<section class="glass p-4 mt-4"><h2>Update status</h2><?php if($transitions[$order['status']]): ?><form method="post" class="search-inline"><?= csrf() ?><input type="hidden" name="id" value="<?= $order['id'] ?>"><select name="status" class="form-select" aria-label="New order status"><?php foreach($transitions[$order['status']] as $s): ?><option><?= e($s) ?></option><?php endforeach; ?></select><button class="btn btn-accent">Save status</button></form><p class="small mt-3">Cancelling restores stock exactly once. Shipped and completed orders cannot be cancelled here.</p><?php else: ?><p>This order has reached its final status.</p><?php endif; ?></section><a class="btn btn-link mt-4" href="<?= url('admin/orders.php') ?>">← All orders</a>
<?php else: ?><form method="get" class="search-inline mb-4"><input name="q" class="form-control" value="<?= e(get('q')) ?>" placeholder="Order number or customer name" aria-label="Search orders"><select name="status" class="form-select" aria-label="Filter order status"><option value="">All statuses</option><?php foreach(array_keys($transitions) as $s): ?><option <?= get('status')===$s?'selected':'' ?>><?= $s ?></option><?php endforeach; ?></select><button class="btn btn-soft">Filter</button></form><div class="glass table-responsive p-3"><table class="table"><thead><tr><th>Order</th><th>Customer</th><th>Date</th><th>Payment</th><th>Status</th><th>Total</th></tr></thead><tbody><?php $params=['%'.get('q').'%','%'.get('q').'%']; $filter=''; if(isset($transitions[get('status')])) { $filter=' AND status=?'; $params[]=get('status'); } foreach(all('SELECT * FROM orders WHERE (order_number LIKE ? OR full_name LIKE ?)'.$filter.' ORDER BY id DESC',$params) as $row): ?><tr><td><a href="<?= url('admin/orders.php?id='.$row['id']) ?>"><?= e($row['order_number']) ?> ↗</a></td><td><?= e($row['full_name']) ?></td><td><?= e($row['created_at']) ?></td><td><?= e($row['payment_status']) ?></td><td><span class="status"><?= e($row['status']) ?></span></td><td><?= money($row['total']) ?></td></tr><?php endforeach; ?></tbody></table></div><?php endif; require __DIR__.'/_footer.php'; ?>
