<?php
require dirname(__DIR__).'/includes/functions.php'; require_admin(); $error='';
if($_SERVER['REQUEST_METHOD']==='POST') {
 check_csrf();
 try {
  $id=(int)post('id'); $existing=$id?one('SELECT * FROM products WHERE id=?',[$id]):null;
  if($id && !$existing) throw new DomainException('Product not found.');
  if(post('action')==='delete') { q('UPDATE products SET active=0 WHERE id=?',[$id]); flash('Product removed from the storefront. Order history is preserved.'); go('admin/products.php'); }
  if(post('action')!=='save') throw new DomainException('Unknown action.');
  $name=require_text(post('name'),'Name',2,150); $description=require_text(post('description'),'Description',10,10000); $category=(int)post('category_id');
  if(!one('SELECT id FROM categories WHERE id=?',[$category])) throw new DomainException('Choose a category.');
  $price=filter_var(post('price'),FILTER_VALIDATE_FLOAT); $sale=post('sale_price')===''?null:filter_var(post('sale_price'),FILTER_VALIDATE_FLOAT); $stock=filter_var(post('stock'),FILTER_VALIDATE_INT);
  if($price===false || $price<=0 || $price>9999999999 || ($sale!==null && ($sale===false || $sale<0 || $sale>$price)) || $stock===false || $stock<0 || $stock>1000000) throw new DomainException('Enter valid prices and a stock quantity from 0 to 1,000,000.');
  $sizes=post('sizes'); $colors=post('colors'); foreach([$sizes,$colors] as $csv) { if(strlen($csv)>255) throw new DomainException('Options are too long.'); foreach(options($csv) as $v) if(mb_strlen($v)>40) throw new DomainException('Each option must be at most 40 characters.'); }
  $keywords=post('keywords'); if(mb_strlen($keywords)>255) throw new DomainException('Keywords must be at most 255 characters.');
  $image=upload_image('image') ?? ($existing['image'] ?? 'assets/images/electronics.svg');
  $data=[$category,$name,$description,$keywords,$price,$sale,$stock,$image,$sizes,$colors,isset($_POST['active'])?1:0];
  db()->beginTransaction();
  if($id) q('UPDATE products SET category_id=?,name=?,description=?,keywords=?,price=?,sale_price=?,stock=?,image=?,sizes=?,colors=?,active=? WHERE id=?',array_merge($data,[$id]));
  else { q('INSERT INTO products(category_id,name,description,keywords,price,sale_price,stock,image,sizes,colors,active) VALUES(?,?,?,?,?,?,?,?,?,?,?)',$data); $id=(int)db()->lastInsertId(); }
  if($gallery=upload_image('gallery')) q('INSERT INTO product_images(product_id,image) VALUES(?,?)',[$id,$gallery]);
  foreach((array)($_POST['remove_images'] ?? []) as $imageId) q('DELETE FROM product_images WHERE id=? AND product_id=?',[(int)$imageId,$id]);
  db()->commit(); flash('Product saved.'); go('admin/products.php?edit='.$id);
 } catch(DomainException $ex) { if(db()->inTransaction()) db()->rollBack(); $error=$ex->getMessage(); }
}
$edit=(int)get('edit'); $p=$edit?one('SELECT * FROM products WHERE id=?',[$edit]):null; $title='Products'; require __DIR__.'/_header.php'; ?>
<div class="section-heading"><p>Manage your collection, pricing and stock.</p><a class="btn btn-accent" href="<?= url('admin/products.php?new=1') ?>">+ Add product</a></div>
<?php if($p || get('new') || $error): ?><section class="glass p-4 mb-4"><h2><?= $p?'Edit product':'New product' ?></h2><form method="post" enctype="multipart/form-data"><?= csrf() ?><input type="hidden" name="id" value="<?= (int)($p['id'] ?? 0) ?>"><div class="row g-3"><?php foreach(['name'=>'Product name','keywords'=>'Search keywords','price'=>'Price (₱)','sale_price'=>'Sale price (optional)','stock'=>'Stock','sizes'=>'Sizes (comma separated)','colors'=>'Colors (comma separated)'] as $key=>$label): ?><div class="col-md-6"><label><?= $label ?><input class="form-control" name="<?= $key ?>" value="<?= e(post($key,(string)($p[$key] ?? ''))) ?>" <?= in_array($key,['price','sale_price','stock'])?'type="number" min="0" step="'.($key==='stock'?'1':'0.01').'"':'type="text"' ?> <?= in_array($key,['name','price','stock'])?'required':'' ?>></label></div><?php endforeach; ?><div class="col-md-6"><label>Category<select name="category_id" class="form-select"><?php foreach(categories() as $c): ?><option value="<?= $c['id'] ?>" <?= (int)post('category_id',(string)($p['category_id'] ?? 0))===$c['id']?'selected':'' ?>><?= e($c['name']) ?></option><?php endforeach; ?></select></label></div></div><label>Description<textarea name="description" rows="4" class="form-control" required><?= e(post('description',$p['description'] ?? '')) ?></textarea></label><div class="row"><label class="col-md-6">Main image (JPG, PNG, WebP · max 4 MB)<input name="image" type="file" accept="image/jpeg,image/png,image/webp" class="form-control"></label><label class="col-md-6">Add gallery image<input name="gallery" type="file" accept="image/jpeg,image/png,image/webp" class="form-control"></label></div><?php if($p): ?><div class="gallery-thumbs mb-3"><?php foreach(all('SELECT * FROM product_images WHERE product_id=?',[$p['id']]) as $im): ?><label><img src="<?= image_url($im['image']) ?>" width="100" height="84" alt="Gallery image"><span class="d-block"><input type="checkbox" name="remove_images[]" value="<?= $im['id'] ?>"> Remove</span></label><?php endforeach; ?></div><p>Rating: <?= e($p['rating']) ?> / 5 (calculated from customer reviews)</p><?php endif; ?><label class="check-label"><input type="checkbox" name="active" <?= ($p['active'] ?? 1)?'checked':'' ?>> Visible in store</label><button class="btn btn-accent" name="action" value="save">Save product</button></form></section><?php endif; ?>
<form class="search-inline mb-3" method="get"><input name="q" class="form-control" value="<?= e(get('q')) ?>" placeholder="Search products" aria-label="Search products"><button class="btn btn-soft">Search</button></form><div class="glass p-3 table-responsive"><table class="table align-middle"><thead><tr><th>Product</th><th>Price</th><th>Stock</th><th>Visibility</th><th>Actions</th></tr></thead><tbody><?php foreach(all('SELECT * FROM products WHERE name LIKE ? ORDER BY id DESC',['%'.get('q').'%']) as $row): ?><tr><td><img class="table-image" src="<?= image_url($row['image']) ?>" alt=""> <?= e($row['name']) ?></td><td><?= money(price($row)) ?></td><td><?= $row['stock'] ?></td><td><?= $row['active']?'Active':'Archived' ?></td><td><div class="d-flex gap-2"><a class="btn btn-soft btn-sm" href="<?= url('admin/products.php?edit='.$row['id']) ?>">Edit</a><form method="post" data-confirm="Remove this product from the storefront?"><?= csrf() ?><input type="hidden" name="id" value="<?= $row['id'] ?>"><button name="action" value="delete" class="btn btn-outline-danger btn-sm">Delete</button></form></div></td></tr><?php endforeach; ?></tbody></table></div><?php require __DIR__.'/_footer.php'; ?>
